modules/contratti/edit.php
modules/fatture/edit.php
modules/interventi/edit.php
modules/ordini/edit.php
modules/preventivi/edit.php

aggiunto link alla scheda anagrafica ed alla scheda agente dove presente
nei moduli interventi,fatture,ordini,preventivi,contratti

richiesta #104

---

src/Update.php

Fix mancata assegnazione a variabile per utilizzo con "end"

Risoluzione problema installazione, Fix #130

---

modules/pagamenti/edit.php

Correzione variabile sbagliata per abbinamento al select in edit.php nel modulo pagamenti

Fix errore pagamenti #129

---

templates/interventi/body.php

Inserita la possibilità di stampare la partita iva se il cliente ne è in possesso (vedi se il cliente è un'azienda o una società)
Risolve: #(issue)

possibilità di stampare la p.iva se il cliente ne è in possesso

---

actions.php
src/Prints.php

Fix allegati multipli attività
Risolve: #175

fix allegati multipli email

---

.github/CONTRIBUTING.md

Correzione link del sito EditorConfig che non era corretto
Includi un sommario dei cambiamenti introdotti, con il relativo contesto.
Elenca anche le eventuali dipendenze aggiuntive richieste per questa modifica.
Risolve: #(issue)

Aggiornamento pagina CONTRIBUTING

---

composer.json
update/2_4_10.php
update/2_4_9.php
update/v2_4_10/Anagrafica.php
update/v2_4_10/Fattura.php
update/v2_4_10/Riga.php
update/v2_4_10/TipoAnagrafica.php
update/v2_4_10/TipoFattura.php

Correzioni per l'utilizzo di classi nell'aggiornamento alla versione 2.4.10, per evitare problemi causati dalla sovrascrizione di alcuni metodi nelle versioni successive (per esempio, per le dichiarazioni d'intento).

Correzioni per l'utilizzo delle classi v2.4.10

---

modules/fatture/src/Fattura.php
modules/scadenzario/src/Scadenza.php

Miglioramento del metodo di individuazione delle scadenze per la ritenuta d'acconto tramite i metodi eloquent.
Da testare perchè al momento in locale non mi funziona MySQL :(

Miglioramento date scadenze

---

modules/fatture/add_intervento.php

Escludi interventi associati ad un ordine
Aggiunto nel where filtro per interventi associati ad un ordine
Risolve: BUG: Generazione errata numero intervento per anno precedente #737

Fix fatturazione interventi associati a contratto

---

update/2_4_13.sql

resolve #771 considerando che l'altro bug segnalato si applica a codice vecchio

corretto escaping per selezione hook aggiornamenti

---

update/2_4_16.sql

Mancava il punto e virgola alla fine della query, che quindi mandava in crash il processo di aggiornamento

Fix query di update views

---

modules/stampe_contabili/edit.php
modules/stampe_contabili/stampa_registro_iva.php
plugins/exportFE/actions.php
plugins/exportFE/edit.php
plugins/exportFE/src/Interaction.php
templates/registro_iva/init.php
templates/registro_iva/piece.php
templates/registro_iva/settings.php
templates/registro_iva/top.php

- Introduzione base per operazioni di verifica notifica FE
- Aggiunta scelta del sezionale prima della stampa del registro IVA

Verifica notifica fe

---

core.php

Questa fix corregge una vulnerabilità di tipo CSRF.

Fix vulnerabilità CSRF

---

modules/fatture/src/Gestori/Bollo.php

Fix risolve implemetazione marca da bollo automatica in fattura

Fix marca da bollo automatica al cliente

---

templates/contratti_cons/top.php
templates/ordini_cons/top.php
templates/preventivi_cons/top.php

Modifica intestazione (top.php) stampa consuntivo Contratti/Ordini/Preventivi così da riflettere le modifiche apportate da @MatteoPistorello alla stampa Riepilogo Interventi (Miglioramenti stampa riepilogo interventi).

Adeguamento stampe consuntivo

---

plugins/pianificazione_fatturazione/actions.php

Possibile soluzione per la issue #1008
Aggiunto il controllo sull'id record del contratto
Risolve: #1008

Rimuovendo la pianificazione fatturazione vengono eliminate tutte le pianificazioni, anche di altri contratti #1008

---

modules/tipi_intervento/actions.php

Risolto uso di variabile non inizializzata
Risolve: #1014

Risolta issue #1014

---

index.php

I CSS personalizzati possono essere molto comodi ma attualmente non sono supportati nella pagina di login.
Questo commit abilita i CSS personalizzati anche in quella pagina

[proposta] Aggiungere CSS personalizzati anche nella pagina di login

---

include/common/descrizione.php

Fix note interne in riga documento
Risolve: #1127 

Fix note interne riga documento (#1127)

---

lib/helpers.php

La forma corretta della valuta è CURRENCY IMPORTO. Attualmente è configurata come IMPORTO CURRENCY.

Miglioria minore: corretta forma della valuta

---

src/Notifications/EmailNotification.php

bug richiesta notifica lettura email mancante

---

modules/dashboard/widgets/notifiche.php

È stato aggiunto la visualizzazione nel widget dashboard delle note interne  genererate nello scadenzario.

mancata visualizzazione note scadenzario da widget Dashboard

---

docker/Dockerfile
docker/docker-compose.yml
docker/php.ini

Ciao ho creato dei file per dockerare l’applicativo openstamanager
provate ad entrare nella cartella docker e lanciate il comando "docker compose up --build -d"
Dovrebbe generare una app docker con dentro openstamanager e un mysql (per vedere l'ip della "macchina" MYSQL fare docker inspect mysql) . L'applicativo dovrebbe rispondere alla porta 8090 in localhost
(se può interessare altrimenti rigettate la pull)
Ciao e Buon Anno
Risolve: #(issue)
- [X ] Questo cambiamenti richiede un aggiornamento della documentazione
non applicabile

Creazione docker del progetto openstamanager

---

modules/articoli/bulk.php

Possibilità, in azioni di gruppo, di poter attivare/disattivare massivamente gli articoli selezionati.
Risolve: #1585

fix: #1585 possibilità, in azioni di gruppo, di poter attivare/disattivare massivamente gli articoli selezionati

---

.yarnrc.yml
package.json

Update Yarn to work with latest version.

yarn update
